INPUT_DIR1:
  PATH: Drell-Yan
  EVENTS: 50k
  EVENTS_VALIDATION: 100k
  REWEIGHTING: on
  VALIDATION_REWEIGHTING: on

INPUT_DIR2:
  PATH: Jets
  EVENTS: 75k
  EVENTS_VALIDATION: 150k
  REWEIGHTING: on
  VALIDATION_REWEIGHTING: on

MASTER_DIR: master
MERGED_DIR: merged

N_GRID: 50
SURROGATE_ORDER: 2,0
PATTERN: MPI+RECONNECTIONS.v

SHERPA_BINARY:           ~/Programs/sherpa-ue/install/bin/Sherpa
SHERPA_ON_THE_ROCKS_DIR: ~/sherpa-on-the-rocks
APP_TOOLS_INSTALLATION:  ~/Programs/local/bin
APPRENTICE_INSTALLATION: ~/Programs/local/bin
RIVET_ENV_SCRIPT:        ~/Programs/local/rivetenv.sh