INPUT_DIR1:
  PATH: Drell-Yan
  EVENTS: 50k
  EVENTS_VALIDATION: 100k

N_GRID: 50
SURROGATE_ORDER: 2,0

RIVET_ENV_SCRIPT:        ~/Programs/local/rivetenv.sh
SHERPA_ON_THE_ROCKS_DIR: ~/sherpa-on-the-rocks
APP_TOOLS_INSTALLATION:  ~/Programs/local/bin
APPRENTICE_INSTALLATION: ~/Programs/local/bin
SHERPA_BINARY:           ~/Programs/sherpa/install/bin/Sherpa