set(libProc_2_3__G__ub__d__db__ub__O3_0_la_SOURCES 
V_1.C
V.C
V_Z.C
)
add_library(Proc_2_3__G__ub__d__db__ub__O3_0SHARED${libProc_2_3__G__ub__d__db__ub__O3_0_la_SOURCES})
amegic_handle_shared_library(Proc_2_3__G__ub__d__db__ub__O3_0)
install(TARGETS Proc_2_3__G__ub__d__db__ub__O3_0 DESTINATION ${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR})


